[package]
name = "ode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ode_solvers = "0.3.7"
plotlib = "0.5.1"

[[examples]]
name = "harmonic_oscillator"
path = "examples/harmonic_oscillator.rs"
